BEGIN

INSERT INTO USERS (USERNAME, PASWORD, ADRESS, EMAIL, TELEPHONE) VALUES ('EDUARDO', '1234', 'MADRID', 'eduardo@gmail.com', '222222222');
INSERT INTO USERS (USERNAME, PASWORD, ADRESS, EMAIL, TELEPHONE) VALUES ('CRISTINA', '1234', 'VALENCIA', 'cristina@gmail.com', '33333333');
INSERT INTO USERS (USERNAME, PASWORD, ADRESS, EMAIL, TELEPHONE) VALUES ('HECTOR', '1234', 'ZARAGOZA', 'hector@gmail.com', '111111111');

INSERT INTO STYLES (STYLE_ID, STYLE_NAME) VALUES ('1', 'MANGA CORTA');
INSERT INTO STYLES (STYLE_ID, STYLE_NAME) VALUES ('2', 'MANGA LARGA');
INSERT INTO STYLES (STYLE_ID, STYLE_NAME) VALUES ('3', 'BASICA');


INSERT INTO CLOTHES (STYLE_ID, COLLECTION, CLOTHES_NAME, PRICE) VALUES ('1','VERANO','CAMISETA','10');
INSERT INTO CLOTHES (STYLE_ID, COLLECTION, CLOTHES_NAME, PRICE) VALUES ('2','PRIMAVERA','CAMISETA','20');
INSERT INTO CLOTHES (STYLE_ID, COLLECTION, CLOTHES_NAME, PRICE) VALUES ('3','INVIERNO','PANTALON','55');
INSERT INTO CLOTHES (STYLE_ID, COLLECTION, CLOTHES_NAME, PRICE) VALUES ('3','VERANO','PANTALON','40');

INSERT INTO ORDERS (USERNAME, ORDER_DATE) VALUES ('CRISTINA','14/06/2022');
INSERT INTO ORDERS (USERNAME, ORDER_DATE) VALUES ('EDUARDO','20/07/2022');
INSERT INTO ORDERS (USERNAME, ORDER_DATE) VALUES ('HECTOR','15/08/2022');

COMMIT;
END;

SELECT * FROM USERS ;
SELECT * FROM STYLES;
SELECT * FROM CLOTHES;
SELECT * FROM ORDERS;




SELECT STYLE_NAME ,COLLECTION, CLOTHES_NAME 
FROM STYLES ST JOIN CLOTHES CL  
ON ST.STYLE_ID = CL.STYLE_ID  
WHERE INSTR (STYLE_NAME ,'BAS')!=0;



SELECT STYLE_NAME ,COLLECTION, CLOTHES_NAME 
FROM STYLES ST JOIN CLOTHES CL  ON ST.STYLE_ID = CL.STYLE_ID  
WHERE INSTR(STYLE_NAME,'ON') != 0 OR INSTR(COLLECTION, 'ON') != 0 OR INSTR(CLOTHES_NAME,'ON') != 0;

